import './globals.css';

export const metadata = {
  title: 'Learners - Master Any Concept',
  description: '1-on-1 mentorship to master any concept or logic.',
  // Open Graph metadata is automatically generated by app/opengraph-image.jsx
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@400;500;700;800&display=swap" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
