export const courses = [
    {
        id: 1,
        title: 'React Hooks Logic',
        level: 'Intermediate',
        courseCode: 'RCT-101',
        category: 'Frontend',
        instructor: { name: 'David Adewale', bio: 'Senior Frontend Engineer with 8 years of React experience.' },
        duration: '1 Hour',
        sessions: 2,
        cost: 15000,
        image: '/web_dev_course_1770743142604.png',
        outline: ['Understanding closure in hooks', 'Custom hooks design patterns', 'Performance optimization', 'Rules of hooks deep dive'],
    },
    {
        id: 2,
        title: 'Backend API Architecture',
        level: 'Advanced',
        courseCode: 'BND-202',
        category: 'Backend',
        instructor: { name: 'Sarah O.', bio: 'System Architect specializing in scalable Node.js applications.' },
        duration: '1.5 Hours',
        sessions: 3,
        cost: 25000,
        image: '/web_dev_course_1770743142604.png',
        outline: ['REST vs GraphQL', 'Database design for scale', 'Authentication & Authorization', 'Microservices patterns'],
    },
    {
        id: 3,
        title: 'UI/UX Design Principles',
        level: 'Beginner',
        courseCode: 'DSN-101',
        category: 'Design',
        instructor: { name: 'Michael K.', bio: 'Product Designer who has led design teams at top startups.' },
        duration: '1 Hour',
        sessions: 2,
        cost: 12000,
        image: '/ui_ux_design_1770743161460.png',
        outline: ['Visual Hierarchy', 'Color Theory', 'Typography basics', 'Figma Pro tips'],
    },
    {
        id: 4,
        title: 'Advanced JS Closures',
        level: 'Advanced',
        courseCode: 'JS-303',
        category: 'Language',
        instructor: { name: 'Chisom E.', bio: 'JavaScript expert and technical writer.' },
        duration: '1 Hour',
        sessions: 1,
        cost: 10000,
        image: '/web_dev_course_1770743142604.png',
        outline: ['Lexical Scope', 'Execution Context', 'Memory Management', 'Practical Closure Use Cases'],
    },
    {
        id: 5,
        title: 'Data Structures: Graphs',
        level: 'Hard',
        courseCode: 'CS-401',
        category: 'Computer Science',
        instructor: { name: 'Dr. Tunde', bio: 'CS Professor with a passion for simplifying algorithms.' },
        duration: '2 Hours',
        sessions: 4,
        cost: 30000,
        image: '/data_science_course_1770743181838.png',
        outline: ['Graph theory basics', 'BFS vs DFS', 'Shortest Path Algorithms', 'Real-world applications'],
    },
    {
        id: 6,
        title: 'Next.js App Router',
        level: 'Intermediate',
        courseCode: 'NXT-201',
        category: 'Fullstack',
        instructor: { name: 'Lala Tech', bio: 'Fullstack developer building modern web apps.' },
        duration: '1.5 Hours',
        sessions: 3,
        cost: 20000,
        image: '/web_dev_course_1770743142604.png',
        outline: ['Server Components', 'Routing Patterns', 'Data Fetching', 'SEO Optimization'],
    },
    {
        id: 7,
        title: 'Python for Data Science',
        level: 'Beginner',
        courseCode: 'PY-101',
        category: 'Data Science',
        instructor: { name: 'Aminat Lawal', bio: 'Data Scientist at a top fintech.' },
        duration: '1.5 Hours',
        sessions: 3,
        cost: 18000,
        image: '/data_science_course_1770743181838.png',
        outline: ['Python basics', 'Pandas & NumPy', 'Data Visualization', 'Intro to ML'],
    },
    {
        id: 8,
        title: 'Cybersecurity Essentials',
        level: 'Beginner',
        courseCode: 'SEC-101',
        category: 'Cybersecurity',
        instructor: { name: 'Emmanuel Jacobs', bio: 'Certified Ethical Hacker.' },
        duration: '1 Hour',
        sessions: 2,
        cost: 15000,
        image: '/cybersecurity_course_1770743238179.png',
        outline: ['Network Security', 'Common Vulnerabilities', 'Encryption basics', 'Security Best Practices'],
    },
    {
        id: 9,
        title: 'Mobile App Dev with React Native',
        level: 'Intermediate',
        courseCode: 'MOB-201',
        category: 'Mobile',
        instructor: { name: 'Tobi S.', bio: 'Mobile developer with 5+ published apps.' },
        duration: '1.5 Hours',
        sessions: 3,
        cost: 22000,
        image: '/mobile_dev_course_1770743219489.png',
        outline: ['Expo framework', 'Native Components', 'Navigation', 'Publishing to Stores'],
    },
    {
        id: 10,
        title: 'DevOps & CI/CD Pipelines',
        level: 'Advanced',
        courseCode: 'OPS-301',
        category: 'DevOps',
        instructor: { name: 'Victor O.', bio: 'DevOps Engineer managing cloud infrastructure.' },
        duration: '2 Hours',
        sessions: 3,
        cost: 28000,
        image: '/cybersecurity_course_1770743238179.png',
        outline: ['Docker Containers', 'GitHub Actions', 'AWS Basics', 'Automated Testing'],
    },
    {
        id: 11,
        title: 'Product Management 101',
        level: 'Beginner',
        courseCode: 'PM-101',
        category: 'Product',
        instructor: { name: 'Grace N.', bio: 'Senior PM at a software agency.' },
        duration: '1 Hour',
        sessions: 2,
        cost: 12000,
        image: '/digital_marketing_course_1770743199650.png',
        outline: ['Product Lifecycle', 'User Research', 'Agile/Scrum', 'Roadmapping'],
    },
    {
        id: 12,
        title: 'Figma Auto-Layout Mastery',
        level: 'Intermediate',
        courseCode: 'DSN-202',
        category: 'Design',
        instructor: { name: 'Michael K.', bio: 'Product Designer.' },
        duration: '1 Hour',
        sessions: 1,
        cost: 8000,
        image: '/ui_ux_design_1770743161460.png',
        outline: ['Auto-layout basics', 'Responsive components', 'Complex nesting', 'Design systems'],
    },
    {
        id: 13,
        title: 'SQL Database Optimization',
        level: 'Advanced',
        courseCode: 'DB-301',
        category: 'Backend',
        instructor: { name: 'Sarah O.', bio: 'System Architect.' },
        duration: '1.5 Hours',
        sessions: 2,
        cost: 20000,
        image: '/data_science_course_1770743181838.png',
        outline: ['Indexing strategies', 'Query analyzing', 'Normalization', 'ACID properties'],
    },
    {
        id: 14,
        title: 'Introduction to Blockchain',
        level: 'Beginner',
        courseCode: 'WEB3-101',
        category: 'Web3',
        instructor: { name: 'Daniel K.', bio: 'Blockchain developer.' },
        duration: '1 Hour',
        sessions: 2,
        cost: 16000,
        image: '/cybersecurity_course_1770743238179.png',
        outline: ['How Blockchain works', 'Smart Contracts', 'Wallets', 'DeFi basics'],
    },
    {
        id: 15,
        title: 'Digital Marketing Strategy',
        level: 'Intermediate',
        courseCode: 'MKT-201',
        category: 'Marketing',
        instructor: { name: 'Femi A.', bio: 'Digital Marketing Strategist.' },
        duration: '1.5 Hours',
        sessions: 3,
        cost: 14000,
        image: '/digital_marketing_course_1770743199650.png',
        outline: ['SEO Fundamentals', 'Social Media Ads', 'Content Strategy', 'Analytics'],
    },
    {
        id: 16,
        title: 'Vue.js Composition API',
        level: 'Intermediate',
        courseCode: 'VUE-201',
        category: 'Frontend',
        instructor: { name: 'Lala Tech', bio: 'Fullstack Developer.' },
        duration: '1 Hour',
        sessions: 2,
        cost: 13000,
        image: '/web_dev_course_1770743142604.png',
        outline: ['Reactivity', 'Setup function', 'Lifecycle hooks', 'State Management'],
    },
    {
        id: 17,
        title: 'Machine Learning Algorithms',
        level: 'Advanced',
        courseCode: 'ML-301',
        category: 'Data Science',
        instructor: { name: 'Aminat Lawal', bio: 'Data Scientist.' },
        duration: '2 Hours',
        sessions: 4,
        cost: 35000,
        image: '/data_science_course_1770743181838.png',
        outline: ['Linear Regression', 'Neural Networks', 'Model Training', 'Python scikit-learn'],
    },
    {
        id: 18,
        title: 'Ethical Hacking Lab',
        level: 'Advanced',
        courseCode: 'SEC-301',
        category: 'Cybersecurity',
        instructor: { name: 'Emmanuel Jacobs', bio: 'Ethical Hacker.' },
        duration: '2 Hours',
        sessions: 3,
        cost: 40000,
        image: '/cybersecurity_course_1770743238179.png',
        outline: ['Penetration Testing', 'Kali Linux', 'Exploit Frameworks', 'Reporting'],
    }
];
